version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/app_db
      SECRET_KEY: supersecrffydurhgsjdet
    #command: bash -c "alembic revision --autogenerate && alembic upgrade head"
    

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_PORT: 5432
      POSTGRES_SERVER: db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
